### ISSUE TITLE
[Bug] `AttributeError: module 'torch' has no attribute 'xla'` after upgrading trl 0.21.0 > 0.22.0

### ISSUE THREAD

**Issue by steveepreston** [huggingface/trl#4182]
### Reproduction

```python
from trl import SFTTrainer
trainer = SFTTrainer(...)
trainer.train()
```

Faced this error after upgrading trl from 0.21.0  > 0.22.0

Full log:

```python
File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:2238, in Trainer.train(self, resume_from_checkpoint, trial, ignore_keys_for_eval, **kwargs)
   2236         hf_hub_utils.enable_progress_bars()
   2237 else:
-> 2238     return inner_training_loop(
   2239         args=args,
   2240         resume_from_checkpoint=resume_from_checkpoint,
   2241         trial=trial,
   2242         ignore_keys_for_eval=ignore_keys_for_eval,
   2243     )

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:2582, in Trainer._inner_training_loop(self, batch_size, args, resume_from_checkpoint, trial, ignore_keys_for_eval)
   2575 context = (
   2576     functools.partial(self.accelerator.no_sync, model=model)
   2577     if i != len(batch_samples) - 1
   2578     and self.accelerator.distributed_type != DistributedType.DEEPSPEED
   2579     else contextlib.nullcontext
   2580 )
   2581 with context():
-> 2582     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
   2584 if (
   2585     args.logging_nan_inf_filter
   2586     and not is_torch_xla_available()
   2587     and (torch.isnan(tr_loss_step) or torch.isinf(tr_loss_step))
   2588 ):
   2589     # if loss is nan or inf simply add the average of previous logged losses
   2590     tr_loss = tr_loss + tr_loss / (1 + self.state.global_step - self._globalstep_last_logged)

File /usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:1112, in SFTTrainer.training_step(self, *args, **kwargs)
   1110 def training_step(self, *args, **kwargs):
   1111     with self.maybe_activation_offload_context:
-> 1112         return super().training_step(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:3796, in Trainer.training_step(self, model, inputs, num_items_in_batch)
   3793     return loss_mb.reduce_mean().detach().to(self.args.device)
   3795 with self.compute_loss_context_manager():
-> 3796     loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)
   3798 del inputs
   3799 if (
   3800     self.args.torch_empty_cache_steps is not None
   3801     and self.state.global_step % self.args.torch_empty_cache_steps == 0
   3802 ):

File /usr/local/lib/python3.10/site-packages/trl/trainer/sft_trainer.py:1041, in SFTTrainer.compute_loss(self, model, inputs, return_outputs, num_items_in_batch)
   1039 # If not set, defaults from model config and may warn since cache isn't compatible with gradient checkpointing
   1040 inputs["use_cache"] = False
-> 1041 (loss, outputs) = super().compute_loss(
   1042     model, inputs, return_outputs=True, num_items_in_batch=num_items_in_batch
   1043 )
   1045 # Compute entropy
   1046 if not self.args.use_liger_kernel:  # liger doesn't return logits

File /usr/local/lib/python3.10/site-packages/transformers/trainer.py:3884, in Trainer.compute_loss(self, model, inputs, return_outputs, num_items_in_batch)
   3882         kwargs["num_items_in_batch"] = num_items_in_batch
   3883     inputs = {**inputs, **kwargs}
-> 3884 outputs = model(**inputs)
   3885 # Save past state if it exists
   3886 # TODO: this needs to be fixed and made cleaner later.
   3887 if self.args.past_index >= 0:

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/torch_xla/experimental/spmd_fully_sharded_data_parallel.py:160, in SpmdFullyShardedDataParallel.forward(self, *args, **kwargs)
    159 def forward(self, *args: Any, **kwargs: Any) -> torch.Tensor:
--> 160   output = self.module(*args, **kwargs)
    161   # Need to shard the output of the forward to instruct the compiler
    162   # to enforce the FSDP algorithm.
    163   self._shard_output(output, self._mesh)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1845, in Module._call_impl(self, *args, **kwargs)
   1842     return inner()
   1844 try:
-> 1845     return inner()
   1846 except Exception:
   1847     # run always called hooks if they have not already been run
   1848     # For now only forward hooks have the always_call option but perhaps
   1849     # this functionality should be added to full backward hooks as well.
   1850     for hook_id, hook in _global_forward_hooks.items():

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1793, in Module._call_impl.<locals>.inner()
   1790     bw_hook = BackwardHook(self, full_backward_hooks, backward_pre_hooks)
   1791     args = bw_hook.setup_input_hook(args)
-> 1793 result = forward_call(*args, **kwargs)
   1794 if _global_forward_hooks or self._forward_hooks:
   1795     for hook_id, hook in (
   1796         *_global_forward_hooks.items(),
   1797         *self._forward_hooks.items(),
   1798     ):
   1799         # mark that always called hook is run

File /usr/local/lib/python3.10/site-packages/peft/peft_model.py:1850, in PeftModelForCausalLM.forward(self, input_ids, attention_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict, task_ids, **kwargs)
   1848     with self._enable_peft_forward_hooks(**kwargs):
   1849         kwargs = {k: v for k, v in kwargs.items() if k not in self.special_peft_forward_args}
-> 1850         return self.base_model(
   1851             input_ids=input_ids,
   1852             attention_mask=attention_mask,
   1853             inputs_embeds=inputs_embeds,
   1854             labels=labels,
   1855             output_attentions=output_attentions,
   1856             output_hidden_states=output_hidden_states,
   1857             return_dict=return_dict,
   1858             **kwargs,
   1859         )
   1861 batch_size = _get_batch_size(input_ids, inputs_embeds)
   1862 if attention_mask is not None:
   1863     # concat prompt attention mask

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py:222, in BaseTuner.forward(self, *args, **kwargs)
    221 def forward(self, *args: Any, **kwargs: Any):
--> 222     return self.model.forward(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/transformers/utils/generic.py:959, in can_return_tuple.<locals>.wrapper(self, *args, **kwargs)
    957 if return_dict_passed is not None:
    958     return_dict = return_dict_passed
--> 959 output = func(self, *args, **kwargs)
    960 if not return_dict and not isinstance(output, tuple):
    961     output = output.to_tuple()

File /usr/local/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py:548, in Gemma2ForCausalLM.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, cache_position, logits_to_keep, **kwargs)
    544 output_hidden_states = (
    545     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    546 )
    547 # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
--> 548 outputs: BaseModelOutputWithPast = self.model(
    549     input_ids=input_ids,
    550     attention_mask=attention_mask,
    551     position_ids=position_ids,
    552     past_key_values=past_key_values,
    553     inputs_embeds=inputs_embeds,
    554     use_cache=use_cache,
    555     output_attentions=output_attentions,
    556     output_hidden_states=output_hidden_states,
    557     cache_position=cache_position,
    558     **kwargs,
    559 )
    561 hidden_states = outputs.last_hidden_state
    562 # Only compute necessary logits, and do not upcast them to float if we are not computing the loss

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/transformers/utils/generic.py:1083, in check_model_inputs.<locals>.wrapper(self, *args, **kwargs)
   1080                 module.forward = make_capture_wrapper(module, original_forward, key, specs.index)
   1081                 monkey_patched_layers.append((module, original_forward))
-> 1083 outputs = func(self, *args, **kwargs)
   1084 # Restore original forward methods
   1085 for module, original_forward in monkey_patched_layers:

File /usr/local/lib/python3.10/site-packages/transformers/models/gemma2/modeling_gemma2.py:452, in Gemma2Model.forward(self, input_ids, attention_mask, position_ids, past_key_values, inputs_embeds, use_cache, output_attentions, output_hidden_states, cache_position, **kwargs)
    449 if output_hidden_states:
    450     all_hidden_states += (hidden_states,)
--> 452 layer_outputs = decoder_layer(
    453     hidden_states,
    454     position_embeddings=position_embeddings,
    455     attention_mask=causal_mask_mapping[decoder_layer.attention_type],
    456     position_ids=position_ids,
    457     past_key_value=past_key_values,
    458     output_attentions=output_attentions,
    459     use_cache=use_cache,
    460     cache_position=cache_position,
    461     **kwargs,
    462 )
    464 hidden_states = layer_outputs[0]
    466 if output_attentions:

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1739, in Module._wrapped_call_impl(self, *args, **kwargs)
   1737     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1738 else:
-> 1739     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py:1750, in Module._call_impl(self, *args, **kwargs)
   1745 # If we don't have any hooks, we want to skip the rest of the logic in
   1746 # this function, and just call forward.
   1747 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1748         or _global_backward_pre_hooks or _global_backward_hooks
   1749         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1750     return forward_call(*args, **kwargs)
   1752 result = None
   1753 called_always_called_hooks = set()

File /usr/local/lib/python3.10/site-packages/torch_xla/experimental/spmd_fully_sharded_data_parallel.py:160, in SpmdFullyShardedDataParallel.forward(self, *args, **kwargs)
    159 def forward(self, *args: Any, **kwargs: Any) -> torch.Tensor:
--> 160   output = self.module(*args, **kwargs)
    161   # Need to shard the output of the forward to instruct the compiler
    162   # to enforce the FSDP algorithm.
    163   self._shard_output(output, self._mesh)

File /usr/local/lib/python3.10/site-packages/transformers/modeling_layers.py:93, in GradientCheckpointingLayer.__call__(self, *args, **kwargs)
     90         message = message.rstrip(",") + "."
     91         logger.warning(message)
---> 93     return self._gradient_checkpointing_func(partial(super().__call__, **kwargs), *args)
     94 return super().__call__(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/_compile.py:32, in _disable_dynamo.<locals>.inner(*args, **kwargs)
     29     disable_fn = torch._dynamo.disable(fn, recursive)
     30     fn.__dynamo_disable = disable_fn
---> 32 return disable_fn(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py:745, in DisableContext.__call__.<locals>._fn(*args, **kwargs)
    741 prior_skip_guard_eval_unsafe = set_skip_guard_eval_unsafe(
    742     _is_skip_guard_eval_unsafe_stance()
    743 )
    744 try:
--> 745     return fn(*args, **kwargs)
    746 finally:
    747     _maybe_set_eval_frame(prior)

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:489, in checkpoint(function, use_reentrant, context_fn, determinism_check, debug, *args, **kwargs)
    484     if context_fn is not noop_context_fn or debug is not False:
    485         raise ValueError(
    486             "Passing `context_fn` or `debug` is only supported when "
    487             "use_reentrant=False."
    488         )
--> 489     return CheckpointFunction.apply(function, preserve, *args)
    490 else:
    491     gen = _checkpoint_without_reentrant_generator(
    492         function, preserve, context_fn, determinism_check, debug, *args, **kwargs
    493     )

File /usr/local/lib/python3.10/site-packages/torch/autograd/function.py:575, in Function.apply(cls, *args, **kwargs)
    572 if not torch._C._are_functorch_transforms_active():
    573     # See NOTE: [functorch vjp and autograd interaction]
    574     args = _functorch.utils.unwrap_dead_wrappers(args)
--> 575     return super().apply(*args, **kwargs)  # type: ignore[misc]
    577 if not is_setup_ctx_defined:
    578     raise RuntimeError(
    579         "In order to use an autograd.Function with functorch transforms "
    580         "(vmap, grad, jvp, jacrev, ...), it must override the setup_context "
    581         "staticmethod. For more details, please see "
    582         "https://pytorch.org/docs/main/notes/extending.func.html"
    583     )

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:243, in CheckpointFunction.forward(ctx, run_function, preserve_rng_state, *args)
    238 # Don't eagerly initialize the cuda context by accident.
    239 # (If the user intends that the context is initialized later, within their
    240 # run_function, we SHOULD actually stash the cuda state here.  Unfortunately,
    241 # we have no way to anticipate this will happen before we run the function.)
    242 ctx.had_device_in_fwd = False
--> 243 device_module = _get_device_module(ctx.device_type)
    244 if getattr(device_module, "_initialized", False):
    245     ctx.had_device_in_fwd = True

File /usr/local/lib/python3.10/site-packages/torch/utils/checkpoint.py:95, in _get_device_module(device)
     93 if device == "meta":
     94     return torch.device("meta")
---> 95 device_module = getattr(torch, device)
     96 return device_module

File /usr/local/lib/python3.10/site-packages/torch/__init__.py:2681, in __getattr__(name)
   2678 if name in _lazy_modules:
   2679     return importlib.import_module(f".{name}", __name__)
-> 2681 raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError: module 'torch' has no attribute 'xla'
```

### System Info

- Platform: Linux-6.1.42+-x86_64-with-glibc2.36
- Python version: 3.10.18
- TRL version: unknown
- PyTorch version: 2.6.0
- accelerator(s): cpu
- Transformers version: 4.55.0
- Accelerate version: 1.8.1
- Accelerate config: not found
- Datasets version: 4.1.1
- HF Hub version: 0.35.3
- bitsandbytes version: not installed
- DeepSpeed version: not installed
- Diffusers version: 0.34.0
- Liger-Kernel version: not installed
- LLM-Blender version: not installed
- OpenAI version: not installed
- PEFT version: 0.17.1
- vLLM version: not installed

### Checklist

- [x] I have checked that my issue isn't already filed (see [open issues](https://github.com/huggingface/trl/issues?q=is%3Aissue))
- [x] I have included my system information
- [x] Any code provided is minimal, complete, and reproducible ([more on MREs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any code provided is properly formatted in code blocks, (no screenshot, [more on code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks))
- [x] Any traceback provided is complete

**Comment by steveepreston** [comment]
Fixed by:

```diff
SFTConfig(
+     gradient_checkpointing=False,
)
```

The error raised because `gradient_checkpointing` is setting to `True` by default from `trl 0.22.0`

and this should set to False in TPU env

**Comment by qgallouedec** [comment]
Are you training on TPUs?

**Comment by steveepreston** [comment]
@qgallouedec Yes

**Comment by steveepreston** [comment]
Related docs:





#### There is a document from [AWS Neuron SDK Documentation](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/torch-neuronx/introducing-pytorch-2-x.html#attributeerror-module-torch-has-no-attribute-xla-failure):

In PyTorch 2.x, training scripts might fail during activation checkpointing with the error shown below:
AttributeError: module 'torch' has no attribute 'xla'

The solution is to use `torch_xla.utils.checkpoint.checkpoint` instead of `torch.utils.checkpoint.checkpoint` as the checkpoint function while wrapping pytorch modules for activation checkpointing. Refer to the pytorch/xla discussion regarding this [issue](https://github.com/pytorch/xla/issues/5766). Also set `use_reentrant=True` while calling the torch\_xla checkpoint function. Failure to do so will lead to `XLA currently does not support use_reentrant==False` error. For more details on checkpointing, refer the [documentation](https://pytorch.org/docs/stable/checkpoint.html).

#### But https://github.com/pytorch/xla/issues/6611#issuecomment-1967860548 have another explain:
The native grad ckpt won't work in any cases. We need to apply some special treatment for the XLA compiler to make grad ckpt working.

**Comment by qgallouedec** [comment]
Hey @steveepreston, sorry for the slow reply here, we're catching up on the backlog.

Your diagnosis is right: TRL flipped `gradient_checkpointing` to default `True` in 0.22.0, and native PyTorch gradient checkpointing doesn't work under torch_xla: it calls `getattr(torch, "xla")` in the checkpoint device lookup and blows up.

On TPU/XLA the fix on your side is exactly what you found: pass `gradient_checkpointing=False` (or wire in an XLA-aware checkpoint fn). We don't officially support TPU, so we don't run TPU in CI. Consequently I'll close this one as there is a workaround
