### ISSUE TITLE
ImportError: cannot import name 'SFTConfig' from 'trl'

### ISSUE THREAD

**Issue by brand17** [huggingface/trl#1639]
I installed trl 0.8.6 and tried the example from here https://huggingface.co/docs/trl/main/en/sft_trainer.

I am getting the error in line
`from trl import SFTConfig, SFTTrainer`:

`Exception has occurred: ImportError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
cannot import name 'SFTConfig' from 'trl' (c:\Users\brand17\Documents\Software\python\.env\Lib\site-packages\trl\__init__.py)
  File "H:\My Drive\Colab_Notebooks\CallCenter\simple.py", line 2, in <module>
    from trl import SFTConfig, SFTTrainer, TrainingArguments
  File "C:\Users\brand17\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "C:\Users\brand17\AppData\Local\Programs\Python\Python311\Lib\runpy.py", line 198, in _run_module_as_main (Current frame)
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'SFTConfig' from 'trl' (c:\Users\brand17\Documents\Software\python\.env\Lib\site-packages\trl\__init__.py)`

I work on Windows 10 Pro 22H2 build 19045.4291, python 3.11.4.

**Comment by BaoLocPham** [comment]
Hi @brand17  I also encountered this error, I think in deployment and delivering phase have problem. But after i install from source, it works fine.
I work on Linux, python 3.10 btw.

**Comment by masonwang025** [comment]
@brand17 I also encountered this error, but @BaoLocPham's comment seems to work.
Install from source (`pip install git+https://github.com/huggingface/trl.git`) works.

**Comment by erwe324** [comment]
> @brand17 I also encountered this error, but @BaoLocPham's comment seems to work. Install from source (`pip install git+https://github.com/huggingface/trl.git`) works.

pip install from source works for me also

**Comment by younesbelkada** [comment]
We just made a TRL release, installing the latest TRL should solve the issue `pip install -U trl`
